In [1]:
import pandas as pd
import numpy as np
import sklearn 
from matplotlib import pyplot as plt
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
#df = pd.read_csv('C:/Users/Kate/Desktop/Data Analysis/Datasets/melb_data.csv')

In [3]:
df = pd.read_csv('C:/Users/Kate/Desktop/Data Analysis/Datasets/diamonds.csv')
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [4]:
df2 = df.iloc[np.random.permutation(53940)[:10000]]
df2

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
13470,13471,1.01,Premium,D,SI1,58.9,58.0,5532,6.57,6.54,3.86
15682,15683,0.90,Very Good,E,VVS2,62.2,60.0,6289,6.04,6.12,3.78
27191,27192,2.02,Premium,H,SI1,61.1,60.0,17489,8.19,8.11,4.98
14224,14225,1.38,Ideal,J,SI2,61.0,56.0,5765,7.22,7.26,4.42
20112,20113,1.25,Very Good,G,VS1,62.7,56.0,8580,6.81,6.93,4.31
...,...,...,...,...,...,...,...,...,...,...,...
34944,34945,0.24,Good,E,VS2,63.0,59.0,378,3.96,4.01,2.51
16653,16654,1.53,Fair,J,VS2,64.7,58.0,6659,7.24,7.22,4.68
32674,32675,0.31,Ideal,G,VS1,62.5,57.0,802,4.37,4.34,2.72
43100,43101,0.53,Premium,I,VS1,62.3,58.0,1383,5.26,5.18,3.25
26641,26642,2.03,Very Good,I,VS2,59.9,59.0,16422,8.32,8.24,4.96

In [5]:
X = df2[['carat', 'depth','table']]
Y = df2[['price']]
print(X, Y)
print(X.shape, Y.shape)

       carat  depth  table
13470   1.01   58.9   58.0
15682   0.90   62.2   60.0
27191   2.02   61.1   60.0
14224   1.38   61.0   56.0
20112   1.25   62.7   56.0
...      ...    ...    ...
34944   0.24   63.0   59.0
16653   1.53   64.7   58.0
32674   0.31   62.5   57.0
43100   0.53   62.3   58.0
26641   2.03   59.9   59.0

[10000 rows x 3 columns]        price
13470   5532
15682   6289
27191  17489
14224   5765
20112   8580
...      ...
34944    378
16653   6659
32674    802
43100   1383
26641  16422

[10000 rows x 1 columns]
(10000, 3) (10000, 1)

In [6]:
X,z = sklearn.preprocessing.normalize(X)

ValueError: too many values to unpack (expected 2)

In [ ]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, Y, random_state = 0)

In [ ]:
train_X.shape, test_X.shape, train_y.shape, test_y.shape

In [ ]:
# Define model
diamond_model = LogisticRegression(solver='saga')
# Fit model
diamond_model.fit(train_X, train_y)

In [ ]:
# get predicted prices on validation data
predictions = diamond_model.predict(test_X)

print(mean_absolute_error(test_y, predictions))
print(predictions)